[package]
name = "crypto_utils"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
openssl = "0.10.38"
rand = "0.8.4"

[lib]
path = "src/crypto_utils.rs"
